-- MySQL Script generated by MySQL Workbench
-- Fri Oct 12 16:59:50 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema empresa_fantastica
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema empresa_fantastica
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `empresa_fantastica` DEFAULT CHARACTER SET utf8 ;
USE `empresa_fantastica` ;

-- -----------------------------------------------------
-- Table `empresa_fantastica`.`marca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `empresa_fantastica`.`marca` (
  `id_Marca` INT NOT NULL,
  `nombre_Marca` VARCHAR(45) NULL,
  PRIMARY KEY (`id_Marca`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `empresa_fantastica`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `empresa_fantastica`.`categoria` (
  `id_Categoria` INT NOT NULL,
  `nombre_Categoria` VARCHAR(45) NULL,
  PRIMARY KEY (`id_Categoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `empresa_fantastica`.`modelo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `empresa_fantastica`.`modelo` (
  `id_Modelo` INT NOT NULL,
  `nombre_Modelo` VARCHAR(45) NULL,
  `descripcion` VARCHAR(45) NULL,
  `id_Marca` INT NULL,
  `id_Categoria` INT NULL,
  `precio` FLOAT NULL,
  `consultas` INT(10) NULL,
  PRIMARY KEY (`id_Modelo`),
  INDEX `id_Marca_idx` (`id_Marca` ASC) ,
  INDEX `id_Categoria_idx` (`id_Categoria` ASC) ,
  CONSTRAINT `id_Marca`
    FOREIGN KEY (`id_Marca`)
    REFERENCES `empresa_fantastica`.`marca` (`id_Marca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_Categoria`
    FOREIGN KEY (`id_Categoria`)
    REFERENCES `empresa_fantastica`.`categoria` (`id_Categoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `empresa_fantastica`.`articulo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `empresa_fantastica`.`articulo` (
  `id_Articulo` INT NOT NULL AUTO_INCREMENT,
  `costo` FLOAT NULL,
  `fecha_Compra` DATE NULL,
  `nro_Serie` VARCHAR(45) NULL,
  `id_Modelo` INT NULL,
  PRIMARY KEY (`id_Articulo`),
  INDEX `id_Modelo_idx` (`id_Modelo` ASC) ,
  CONSTRAINT `id_Modelo`
    FOREIGN KEY (`id_Modelo`)
    REFERENCES `empresa_fantastica`.`modelo` (`id_Modelo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `empresa_fantastica`.`tipo_Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `empresa_fantastica`.`tipo_Usuario` (
  `id_Tipo` INT NOT NULL AUTO_INCREMENT,
  `nombre_Tipo` VARCHAR(45) NULL,
  PRIMARY KEY (`id_Tipo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `empresa_fantastica`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `empresa_fantastica`.`usuario` (
  `id_Usuario` INT NOT NULL AUTO_INCREMENT,
  `mail` VARCHAR(45) NULL,
  `clave` VARCHAR(45) NULL,
  `nombre` VARCHAR(45) NULL,
  `apellido` VARCHAR(45) NULL,
  `telefono` VARCHAR(45) NULL,
  `direccion` VARCHAR(45) NULL,
  `id_Tipo` INT NULL,
  PRIMARY KEY (`id_Usuario`),
  UNIQUE INDEX `mail_UNIQUE` (`mail` ASC) ,
  INDEX `id_Tipo_idx` (`id_Tipo` ASC) ,
  CONSTRAINT `id_Tipo`
    FOREIGN KEY (`id_Tipo`)
    REFERENCES `empresa_fantastica`.`tipo_Usuario` (`id_Tipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `empresa_fantastica`.`metodo_Envio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `empresa_fantastica`.`metodo_Envio` (
  `id_Metodo_Envio` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`id_Metodo_Envio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `empresa_fantastica`.`metodo_Pago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `empresa_fantastica`.`metodo_Pago` (
  `id_Metodo_Pago` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`id_Metodo_Pago`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `empresa_fantastica`.`venta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `empresa_fantastica`.`venta` (
  `nro_Factura` INT NOT NULL AUTO_INCREMENT,
  `fecha_Venta` DATE NULL,
  `id_Metodo_Pago` INT NULL,
  `id_Metodo_Envio` INT NULL,
  `id_Usuario` INT NULL,
  PRIMARY KEY (`nro_Factura`),
  INDEX `id_Usuario_idx` (`id_Usuario` ASC) ,
  INDEX `id_Metodo_Envio_idx` (`id_Metodo_Envio` ASC) ,
  INDEX `id_Metodo_Pago_idx` (`id_Metodo_Pago` ASC) ,
  CONSTRAINT `id_Usuario`
    FOREIGN KEY (`id_Usuario`)
    REFERENCES `empresa_fantastica`.`usuario` (`id_Usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_Metodo_Envio`
    FOREIGN KEY (`id_Metodo_Envio`)
    REFERENCES `empresa_fantastica`.`metodo_Envio` (`id_Metodo_Envio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_Metodo_Pago`
    FOREIGN KEY (`id_Metodo_Pago`)
    REFERENCES `empresa_fantastica`.`metodo_Pago` (`id_Metodo_Pago`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `empresa_fantastica`.`ventasXArticulos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `empresa_fantastica`.`ventasXArticulos` (
  `id_Articulos` INT NOT NULL,
  `id_Ventas` INT NOT NULL,
  PRIMARY KEY (`id_Articulos`, `id_Ventas`),
  INDEX `id_Venta_idx` (`id_Ventas` ASC) ,
  CONSTRAINT `id_Articulo`
    FOREIGN KEY (`id_Articulos`)
    REFERENCES `empresa_fantastica`.`articulo` (`id_Articulo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_Venta`
    FOREIGN KEY (`id_Ventas`)
    REFERENCES `empresa_fantastica`.`venta` (`nro_Factura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `empresa_fantastica`.`publicidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `empresa_fantastica`.`publicidad` (
  `id_ModeloPublicidad` INT NOT NULL,
  `fecha_Inicio` DATE NOT NULL,
  `fecha_Fin` DATE NOT NULL,
  `imagen_Banner` VARCHAR(45) NULL,
  `ubicacion` VARCHAR(45) NULL,
  `id_UsuarioPublicidad` INT NULL,
  `descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`fecha_Inicio`, `fecha_Fin`, `id_ModeloPublicidad`),
  INDEX `id_Usuario_idx` (`id_UsuarioPublicidad` ASC, `id_ModeloPublicidad` ASC) ,
  CONSTRAINT `id_ModeloPublicidad`
    FOREIGN KEY (`id_ModeloPublicidad`)
    REFERENCES `empresa_fantastica`.`modelo` (`id_Modelo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_UsuarioPublicidad`
    FOREIGN KEY (`id_UsuarioPublicidad` )
    REFERENCES `empresa_fantastica`.`usuario` (`id_Usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
